### ISSUE TITLE
C-g behaves like RET

### ISSUE THREAD

**Issue by cyrus-and** [raxod502/ctrlf#110] opened 2022-01-09 10:33 UTC
Launch Emacs like this:

```sh
TEMP="$(mktemp -d | tee /dev/stderr)"

cat >"$TEMP/.emacs" <<EOF
(setq custom-file "/dev/null")

(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(package-install 'ctrlf)
EOF

HOME="$TEMP" emacs
```

Then in the Emacs splash screen:

1. `M-x ctrlf-mode`;

2. `C-s emacs`;

3. `C-s` a few more times;

4. `C-g`.

Now the point is left next to the last instance of the match instead of being reset to the original position. 

(Possibly related to #6.)

**Comment by raxod502** [comment] 2022-01-14 23:24
Yeah, I can confirm this happens exactly as you describe it. I'll look into why that could be occurring when I have some time.

**Comment by weirdNox** [comment] 2022-04-24 21:04
For me, just adding the remap of `abort-minibuffers` to `ctrlf-cancel` in `ctrlf-minibuffer-mode-map` fixed this problem!

**Comment by raxod502** [comment] 2022-06-01 16:36
Should be addressed by https://github.com/radian-software/ctrlf/pull/114.

**Comment by weirdNox** [comment] 2022-06-02 09:02
The problem seems to be solved, thank you! ;)

**Closed as completed** 2022-10-24 02:24 UTC
