### ISSUE TITLE
[End of buffer] issue

### ISSUE THREAD

**Issue by failable** [raxod502/ctrlf#46] opened 2020-05-16 11:33 UTC
I'm trying to get rid of `ivy` and `swiper`. When using `ctrlf` to find next search using, my muscle memory make me press <kbd>C-n</kbd> and I get

<img width="722" alt="Screen Shot 2020-05-16 at 7 27 37 PM" src="https://user-images.githubusercontent.com/5475262/82118791-fe4ecb80-97ab-11ea-9fb2-13127d609309.png">

Not a really big issue, and I may forget <kbd>C-n</kbd> and use <kbd>C-s</kbd> instead.

**Comment by raxod502** [comment] 2020-05-16 14:57
Is your intention with `C-n` to exit the search at the current candidate? If so, I don't think that's something I want to support, because the idea of CTRLF is that you don't accidentally exit the search by using any editing commands.

However, the duplicated `[End of buffer]` message is a bug. That does not occur for me with Emacs 28; I assume it is due to a difference in Emacs version. What are you on?

**Comment by failable** [comment] 2020-05-16 15:13
I mean the duplicates and I'm on `GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, Carbon Version 162 AppKit 1894.4)`. I'm also trying to avoid pressing <kbd>C-n</kbd>.

**Comment by raxod502** [comment] 2020-05-17 14:47
During the development since Emacs 26, a bug was introduced relating to minibuffer overlays, and it was subsequently fixed without making it into any release, although the bug stuck around for a while before being fixed. It's possible that you are experiencing this bug. Just to check, can you try it with the latest Emacs build and see if the same problem occurs?

If the bug doesn't occur in either the latest build or in any release, I am reluctant to complicate CTRLF further to work around it.

**Comment by failable** [comment] 2020-05-18 01:07
I build the [latest](https://bitbucket.org/mituharu/emacs-mac/commits/) `emacs-mac` 

```
GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, Carbon Version 162 AppKit 1894.4) of 2020-05-18
```

and the issue is still there.

**Comment by raxod502** [comment] 2020-05-23 15:43
Thank you for the report. I reproduced the issue and believe I fixed it. Please let me know if the change works for you.

**Comment by raxod502** [comment] 2020-08-21 16:31
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)

**Closed as completed by raxod502** 2020-08-21 16:31 UTC
